import { ChartOfAccountItem, BudgetLine } from './types';

// Processed from the provided CSV data
export const CHART_OF_ACCOUNTS: ChartOfAccountItem[] = [
  { code: '1.2', category: 'Local Employees' },
  { code: '1.3 a', category: 'Canadian and International Subcontractors' },
  { code: '1.4 b', category: 'Local Sub-Contractors' },
  { code: '1.6.1', category: 'TRAVEL EXPENSES', isHeader: true },
  { code: '1.6.1.1', category: 'TRAVEL and LIVING EXPENSES FOR PERSONNEL FROM CANADA', isHeader: true },
  { code: '1.6.1.1 a', category: 'International airfares' },
  { code: '1.6.1.1 b', category: 'Regional airfare' },
  { code: '1.6.1.1 c', category: 'Accommodations' },
  { code: '1.6.1.1 d', category: 'Meals' },
  { code: '1.6.1.1 e', category: 'Local Travel' },
  { code: '1.6.1.1 f', category: 'Registration related to obtaining a visa' },
  { code: '1.6.1.2', category: 'REGIONAL TRAVEL IN GHANA FOR LOCAL PERSONNEL (ALINEA STAFF/CONS)', isHeader: true },
  { code: '1.6.1.2 a', category: 'International airfare' },
  { code: '1.6.1.2 b', category: 'Regional airfare' },
  { code: '1.6.1.2 c', category: 'Meals' },
  { code: '1.6.1.2 d', category: 'Accommodations' },
  { code: '1.6.1.2 e', category: 'Local Travel' },
  { code: '1.6.1.2 f', category: 'Vehicle Rental' },
  { code: '1.6.1.3', category: 'REGIONAL TRAVEL IN GHANA FOR LOCAL PERSONNEL (SEND GHANA STAFF)', isHeader: true },
  { code: '1.6.1.3 a', category: 'Regional Airfares (SEND)' },
  { code: '1.6.1.3 b', category: 'Per diems (SEND)' },
  { code: '1.6.1.3 c', category: 'Accommodations (SEND)' },
  { code: '1.6.1.3 d', category: 'Local conveyance (SEND)' },
  { code: '1.6.1.4', category: 'REGIONAL TRAVEL IN GHANA FOR LOCAL PERSONNEL (NETRIGHT STAFF)', isHeader: true },
  { code: '1.6.1.4 a', category: 'Regional Airfares (Netright)' },
  { code: '1.6.1.4 b', category: 'Per diems (Netright)' },
  { code: '1.6.1.4 c', category: 'Accommodations (Netright)' },
  { code: '1.6.1.4 d', category: 'Local Conveyance (Netright)' },
  { code: '1.6.1.5', category: 'REGIONAL TRAVEL IN GHANA FOR LOCAL PERSONNEL (GSS STAFF)', isHeader: true },
  { code: '1.6.1.5 a', category: 'Regional Airfares (SGS)' },
  { code: '1.6.1.5 b', category: 'Local conveyance (SGS)' },
  { code: '1.6.1.5 c', category: 'Per diems (SGS)' },
  { code: '1.6.1.5 d', category: 'Accommodations (SGS)' },
  { code: '1.6.1.6', category: 'TRANSPORTATION AND LIVING COSTS FOR PROJECT TRAINEES', isHeader: true },
  { code: '1.6.1.6 a', category: 'Trainee per diem/meal' },
  { code: '1.6.1.6 b', category: 'Trainee Local conveyance; Trainee travel (inter-city)' },
  { code: '1.6.1.6 c', category: 'Trainee lodging' },
  { code: '1.6.4', category: 'TRAINING EXPENSES', isHeader: true },
  { code: '1.6.4 a', category: 'Facility / training room rental' },
  { code: '1.6.4 b', category: 'Conference package' },
  { code: '1.6.4 c', category: 'Printing / materials' },
  { code: '1.6.4 d', category: 'Workshop supplies' },
  { code: '1.6.4 e', category: 'Workshop refreshments' },
  { code: '1.6.4 f', category: 'Promotional & Networking' },
  { code: '1.6.4 g', category: 'Workshop facilitation' },
  { code: '1.6.4 h', category: 'Awards for GMFs (1214)' },
  { code: 'SEND 1.6.4 i', category: 'Stipends for GMF champions in communities (1211)' },
  { code: 'Netright 1.6.4aj', category: 'Development, Design & Printing of Toolkit' },
  { code: 'Netright 1.6.4k', category: 'Development and printing of a scorecard' },
  { code: 'Netright 1.6.4l', category: 'Course materials, banners, PPEs etc' },
  { code: 'Netright 1.6.4m', category: 'Project promotion, media, publicity, national campaigns, etc.' },
  { code: '1.6.5', category: 'GOODS, ASSETS, AND SUPPLIES', isHeader: true },
  { code: '1.6.5 a', category: 'Vehicle' },
  { code: '1.6.5 b', category: 'Vehicle insurance' },
  { code: '1.6.5 c', category: 'Vehicle fuel' },
  { code: '1.6.5 d', category: 'Vehicle repair / maintenance' },
  { code: '1.6.5 e', category: 'Office furniture (Workstation - desk, chair, filing, bookshelf)' },
  { code: '1.6.5 f', category: 'Printer' },
  { code: '1.6.5 g', category: 'Copier' },
  { code: '1.6.5 h', category: 'Computer' },
  { code: '1.6.5 i', category: 'Projector' },
  { code: '1.6.5 j', category: 'Generator' },
  { code: '1.6.5 k', category: 'Board/meeting room, kitchen, general office cabinetry' },
  { code: '1.6.5 l', category: 'Tablets for M&E surveys' },
  { code: '1.6.5 m', category: 'Statistical Software' },
  { code: '1.6.5 n', category: 'Time-Use Survey Implementation - Tablets' },
  { code: 'SEND 1.6.5 o', category: 'Motor Bike for Field Officers (including registration)' },
  { code: 'SEND 1.6.5 p', category: 'Motor Vehicle' },
  { code: 'SEND 1.6.5 q', category: 'Tablet for Field Officers & M&E Team Backpack' },
  { code: 'SEND 1.6.5 r', category: 'Laptop for Field Officers and Project Officers' },
  { code: 'SEND 1.6.5 s', category: 'Maintenance & Fuel for Field Oficers (Motorbike)' },
  { code: 'SEND 1.6.5 t', category: 'Insurance of Motor Bike, MoT etc' },
  { code: 'SEND 1.6.5 u', category: 'Insurance of Motor Vehicle (comprhensive)' },
  { code: 'SEND 1.6.5 v', category: 'Maintenance & fuel of Motor Vehicle' },
  { code: 'SEND', category: 'GMF Champions logistics (Pens, stationery, notebook, etc)' },
  { code: '1.6.6', category: 'ADMINISTRATION COSTS', isHeader: true },
  { code: '1.6.6 a', category: 'Office rent' },
  { code: '1.6.6 b', category: 'Office leasehold improvements' },
  { code: '1.6.6 c', category: 'Office utilities' },
  { code: '1.6.6 d', category: 'Office expenses and supplies' },
  { code: '1.6.6 e', category: 'Office computer and general maintenance' },
  { code: '1.6.6 f', category: 'Meeting / conference costs' },
  { code: '1.6.6 g', category: 'Seminars and workshops not related to training' },
  { code: '1.6.6 h', category: 'Bank transfer fees' },
  { code: '1.6.6 i', category: 'NGO registration & Legal' },
  { code: 'SEND 1.6.6', category: 'Office expenses and supplies' },
  { code: 'NETRIGHT 1.6.6', category: 'Office expenses and supplies(1221)' },
  { code: '1.6.7', category: 'Other Direct Costs', isHeader: true },
  { code: '1.6.7 a', category: 'Small grants for private sector innovation' },
  { code: '1.6.8', category: 'Volunteer Expenses', isHeader: true },
  { code: '1.6.8 a', category: 'Emergency health travel insurance' },
  { code: '1.6.8 b', category: 'Vaccines' },
  { code: '1.6.8 c', category: 'International airfares' },
  { code: '1.6.8 d', category: 'Regional Airfares' },
  { code: '1.6.8 e', category: 'Local Travel' },
  { code: '1.6.8 f', category: 'Accommodations' },
  { code: '1.6.8 g', category: 'Meals (monthly allowance)' },
  { code: '1.6.8 h', category: 'Expenses related to obtaining a visa' },
  
  // Other Codes from CSV
  { code: 'NB', category: 'Non-billable expense' },
  { code: 'ADV', category: 'Advances' },
  { code: 'CONT', category: 'Contributions to project (cash)' },
  { code: 'TRF', category: 'Transfers' },
  { code: 'ITAX', category: 'Income taxes withheld' },
  { code: 'SSEC', category: 'Social Security Withheld' },
  { code: 'WHT', category: 'With Holding Tax' },
  { code: 'PCA', category: 'Petty Cash Advance' },

  // Non-Expense codes
  { code: 'INCOME_GRANT', category: 'Grant Income' },
  { code: 'INCOME_DONATION', category: 'Private Donations' },
];

export const MOCK_BUDGET: BudgetLine[] = CHART_OF_ACCOUNTS
  .filter(c => !c.isHeader)
  .map(c => ({ code: c.code, monthlyBudget: Math.floor(Math.random() * 5000) + 100 }));